### ISSUE TITLE
-a does not override defaults

### ISSUE THREAD

**Issue by michael-lenz** [mbideau/vcardtools#3]
The -a command line option does not override the default settings, but *adds* to the array.

Was a bit infuriating until I realised that this was what was happening to my contacts.
My workaround was to edit the vcardlib directly and remove the default params.

A good workaround would be to empty/overwrite the array, if -a is supplied.

**Comment by michael-lenz** [comment]
Apart from this bit of "nagging", thanks a lot for this tool; it was a great help! :)

**Comment by mbideau** [comment]
@michael-lenz Thanks a lot for your feedback.  
Sorry for that bug.  
This is fixed now :wink: 
Closing this issue.
