### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by dev-abir** [mbideau/vcardtools#5]
At first, thank you very much, it's a very useful tool...

I can't understand how `--match-attributes MATCH_ATTRIBUTES` exactly works... will it match **all** the attributes I pass, or **any one** of them and merge?

And how to use this?
like this: `--match-attributes ['mobiles', 'names']`
or this: `--match-attributes mobiles names`

And, better if u can provide some common usages/examples and a little bit more detailed documentation...

And, there are some spelling mistakes in the readme file....

**Comment by mbideau** [comment]
Hi @dev-abir,

First, thank you very much for your feedback. It is much appreciated.

I have improved the README as you suggested, with example (at the bottom) and with a better description in the option help message (also reported in the README). See commit f343e3a.
I consider this to be fixed, so I am closing the issue.

Feel free to re-open the issue if you want to add something.

And if you have others suggestions / issues, please open another issue and I will be glad to help you / make changes.

Best regards,
Michael
